services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: "${S3_USER}"
      MINIO_ROOT_PASSWORD: "${S3_PASSWORD}"
    ports:
      - "9000:9000"        # S3 API port
      - "9001:9001"        # Console port
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  minio_data:
  postgres-data:
